### PR TITLE
adding Instant and Duration for better usability

### PR DESCRIPTION
**Pull request by LemonHX**

### CODE REVIEW

**Comment by LemonHX** [comment]
have a check why CI exploded

**Comment by andylokandy** [comment]
I'd like to take the std-like API `Instant` and `Duration`. But why are they enums? In which case it's necessary?

**Comment by Xuanwo** [comment]
Is this PR still going on?

**Comment by andylokandy** [comment]
Thanks to @LemonHX for your hard work! But I've to close it since it's far outdated. If you're interested in making it up to date, a new PR is welcome.

**Pull request closed without merging**
